on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: dotnet build src/TwoLineElements.sln --configuration Release
    - name: Test
      run: dotnet test build src/TwoLineElements.sln --configuration Release --no-build
